-----------------------------------------------------------------------------
--  DATABASE SCHEMA
--
--  TABLE APP_ROLE
--  Role's table
--
--  TABLE APP_RESOURCE
--  Resource's table
--
--  TABLE APP_USER_STATES
--  States for users
--
--  TABLE APP_USER
--  User's table
--
--  TABLE APP_USER_ROLE
--  Relationship between users and its roles
--
-----------------------------------------------------------------------------

-- TABLE APP_ROLE
CREATE TABLE APP_ROLE
(
    ROLE_ID        NUMERIC(2,0)     NOT NULL,
    ROLE_NAME      VARCHAR2(100)    NOT NULL,
    STATE          CHAR(1)          NOT NULL,
    RECORD_DATE    TIMESTAMP        NOT NULL
);

ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_PK
PRIMARY KEY (ROLE_ID);

ALTER TABLE APP_ROLE ADD CONSTRAINT APP_ROLE_STATE_CK
CHECK (STATE IN ('A', 'I'));

CREATE TRIGGER APP_ROLE_BI_TR
BEFORE INSERT ON APP_ROLE
FOR EACH ROW ENABLE
BEGIN
    SELECT SYSDATE INTO :NEW.RECORD_DATE FROM DUAL;
END;
/

-- TABLE APP_RESOURCE
CREATE TABLE APP_RESOURCE
(
    RESOURCE_ID      NUMERIC(2,0)     NOT NULL,
    RESOURCE_NAME    VARCHAR2(100)    NOT NULL,
    STATE            CHAR(1)          NOT NULL,
    RECORD_DATE      TIMESTAMP        NOT NULL
);

ALTER TABLE APP_RESOURCE ADD CONSTRAINT APP_RESOURCE_PK
PRIMARY KEY (RESOURCE_ID);

ALTER TABLE APP_RESOURCE ADD CONSTRAINT APP_RESOURCE_STATE_CK
CHECK (STATE IN ('A', 'I'));

CREATE TRIGGER APP_RESOURCE_BI_TR
BEFORE INSERT ON APP_RESOURCE
FOR EACH ROW ENABLE
BEGIN
    SELECT SYSDATE INTO :NEW.RECORD_DATE FROM DUAL;
END;
/

-- TABLE APP_USER_STATES
CREATE TABLE APP_USER_STATES
(
    USER_STATE_ID    NUMERIC(2,0)     NOT NULL,
    DESCRIPTION      VARCHAR2(100)    NOT NULL
);

ALTER TABLE APP_USER_STATES ADD CONSTRAINT APP_USER_STATES_PK
PRIMARY KEY (USER_STATE_ID);

-- TABLE APP_USER
CREATE TABLE APP_USER
(
    USER_ID          NUMERIC(4,0)    NOT NULL,
    USERNAME         VARCHAR2(20)    NOT NULL,
    USER_STATE_ID    NUMERIC(2,0)    NOT NULL,
    USER_PASSWORD    VARCHAR2(60)    NOT NULL,
    EMAIL            VARCHAR2(50)    NOT NULL,
    TOKEN            VARCHAR2(30)    NULL,
    RECORD_DATE      TIMESTAMP       NOT NULL
);

ALTER TABLE APP_USER ADD CONSTRAINT APP_USER_PK
PRIMARY KEY (USER_ID);

ALTER TABLE APP_USER ADD CONSTRAINT APP_USER_UNIQUE
UNIQUE (USERNAME);

ALTER TABLE APP_USER ADD CONSTRAINT APP_USRS_FK_STATE
FOREIGN KEY (USER_STATE_ID) REFERENCES APP_USER_STATES (USER_STATE_ID);

CREATE TRIGGER APP_USER_BI_TR
BEFORE INSERT ON APP_USER
FOR EACH ROW ENABLE
BEGIN
    SELECT SYSDATE INTO :NEW.RECORD_DATE FROM DUAL;
END;
/

-- TABLE APP_USER_ROLE
CREATE TABLE APP_USER_ROLE
(
    USER_ID    NUMERIC(4,0)    NOT NULL,
    ROLE_ID    NUMERIC(2,0)    NOT NULL
);

ALTER TABLE APP_USER_ROLE ADD CONSTRAINT APP_USER_ROLE_PK
PRIMARY KEY (USER_ID, ROLE_ID);

ALTER TABLE APP_USER_ROLE ADD CONSTRAINT APP_USR_ROLE_FK_USER_ID
FOREIGN KEY (USER_ID) REFERENCES APP_USER (USER_ID);

ALTER TABLE APP_USER_ROLE ADD CONSTRAINT APP_USR_ROLE_FK_ROLE_ID
FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ROLE_ID);

-- TABLE APP_DB_USER_ROLE
-- When authentication is through db, username is not in APP_USER
CREATE TABLE APP_DB_USER_ROLE
(
    USERNAME    VARCHAR2(30 CHAR)    NOT NULL,
    ROLE_ID     NUMERIC(2,0)         NOT NULL
);

ALTER TABLE APP_DB_USER_ROLE ADD CONSTRAINT APP_DB_USR_ROLE_PK
PRIMARY KEY (USERNAME, ROLE_ID);

ALTER TABLE APP_DB_USER_ROLE ADD CONSTRAINT APP_DB_USR_ROLE_FK_ROLE_ID
FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ROLE_ID);


-- BASIC DATA
INSERT INTO APP_USER_STATES (USER_STATE_ID, DESCRIPTION) VALUES (1, 'Pending email');
INSERT INTO APP_USER_STATES (USER_STATE_ID, DESCRIPTION) VALUES (2, 'Active');
