<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "update-form"): ?>

	<?php
		$file = $this->param('file');
	?>

	<form class="ui form" id="frm-update-user-file" data-role="ajax-request" data-response="#edit-user-file-response"
		action="<?= $this->basePath() ?>/public/Workarea/Files/edit" method="post">
		<input type="hidden" name="_conn_id" value="<?= $file->PROJECT_ID ?>" />
		<div class="field">
			<div class="fields">
				<div class="eight wide field">
					<label for="filename"><?= $intl->translate('File name') ?></label>
					<input type="text" id="filename" name="filename" placeholder="<?= $intl->translate('helloworld, firstapp, ...') ?>" value="<?= $file->FILE_NAME ?>" />
				</div>
			</div>
		</div>

		<button class="ui submit button"><i class="check icon"></i> <?= $intl->translate('Save') ?></button>
	</form><br />

	<div id="edit-user-file-response"></div>

<?php elseif ($this->param("process") == "process-response"): ?>

	<div class="ui success message">
		<div class="header">
			<?= $intl->translate('Success') ?>
		</div>
		<p>
			<strong><i class="fas fa-check"></i></strong> <?= $intl->translate('File updated') ?>
		</p>
	</div>

	<script type="text/javascript">
		$("#btn-list-files").trigger("click");
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $intl->translate($this->param("message")) ?>!
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>