<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "register-form"): ?>

	<form class="ui form" id="frm-add-project" data-role="ajax-request" data-response="#add-project-post-response"
		action="<?= $this->basePath() ?>/public/Workarea/Projects/add" method="post">
		<div class="field">
			<div class="fields">
				<div class="eight wide field">
					<label for="projectname"><?= $intl->translate('Project name') ?></label>
					<input type="text" id="projectname" name="projectname" placeholder="<?= $intl->translate('helloworld, firstapp, ...') ?>" />
				</div>
			</div>
		</div>

		<button class="ui submit button"><i class="check icon"></i> <?= $intl->translate('Save') ?></button>
	</form><br />

	<div id="add-project-post-response"></div>

<?php elseif ($this->param("process") == "process-response"): ?>

	<div class="ui success message">
		<div class="header">
			<?= $intl->translate('Success') ?>
		</div>
		<p>
			<strong><i class="fas fa-check"></i></strong> <?= $intl->translate('Project added') ?>
		</p>
	</div>

	<script type="text/javascript">
		$("#frm-add-project")[0].reset();
		$("#btn-list-projects").trigger("click");
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $intl->translate($this->param("message")) ?>!
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>

<script type="text/javascript">
	$('#md-add-project').modal('refresh');
</script>