<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "success"): ?>

	<?php $projects = $this->param('projects'); ?>

	<style>
		.file-list
		{
			list-style-type: none;
			padding-left: 20px;
			margin: 10px 0 0 0;
		}
	</style>

	<?php if (count($projects)): ?>
		<?php foreach ($projects as $project): ?>
			<div class="item" id="user-project-list-item-<?= $project->PROJECT_ID ?>">
			    <div class="right floated content">
					<div class="ui right dropdown item" id="project-options-<?= $project->PROJECT_ID ?>">
						<i class="dropdown icon"></i>
						<div class="menu">
							<div class="header"><?= $project->PROJECT_NAME ?></div>
							<!--<div class="item btn-new-worksheet" data-id="<?= $project->PROJECT_ID ?>" data-name="<?= $project->PROJECT_NAME ?>">
								<i class="icon terminal"></i> <?= $intl->translate('New Worksheet') ?>
							</div>-->
							<div class="item" data-role="ajax-request" data-response="#delete-project-response" data-type="post"
								 data-url="<?= $this->basePath() ?>/public/Workarea/Projects/delete"
								 data-object="v = { id: '<?= $project->PROJECT_ID ?>' }"
								 data-callback="v = {
									before: function() { $('#md-delete-project').modal('show'); },
									success: function() { $('#md-delete-project').modal('refresh'); },
								 }"><i class="icon trash"></i> <?= $intl->translate('Delete') ?></div>
						</div>
					</div>
			    </div>
				<i class="teal large cube middle aligned icon"></i>
				<div class="content view">
					<a class="header" data-url="<?= $this->basePath() ?>/public/Workarea/Projects/edit/id/<?= $project->PROJECT_ID ?>"
						data-role="ajax-request" data-type="get" data-response="#activity-response">
						<?= $project->PROJECT_NAME ?>
					</a>
					<div class="description"><?= $intl->translate('database') ?></div>
				</div>
				<?php if (count($project->files)): ?>
					<ul class="file-list">
						<?php foreach ($project->files as $file): ?>
							<li>
								<?php
									if ($file["type"] == 'DIR'):
										$extension_icon = 'inverted black folder';
									else:
										switch (strstr(strtolower(basename($file["name"])), '.')):
case '.xls':
											case '.xlsx':
											case '.xltx':
												$extension_icon = 'fa-file-excel';
												break;
											case '.pdf':
												$extension_icon = 'fa-file-pdf';
												break;
											case '.jpg':
											case '.jpeg':
											case '.png':
												$extension_icon = 'fa-file-image';
												break;
											case '.doc':
											case '.docx':
											case '.rtf':
												$extension_icon = 'fa-file-word';
												break;
											case '.js':
											case '.json':
												$extension_icon = 'yellow js';
												break;
											case '.php':
												$extension_icon = 'blue code';
												break;
											case '.phar':
												$extension_icon = 'blue file archive';
												break;
											case '.htm':
											case '.html':
											case '.xhtml':
												$extension_icon = 'orange html5';
												break;
											case '.lock':
												$extension_icon = 'secondary lock';
												break;
											case '.txt':
												$extension_icon = 'grey file';
												break;
											default:
												$extension_icon = 'black inverted file';
												break;
										endswitch;
									endif;
								?>

								<?php $action_class = ($file["type"] == 'DIR') ? "btn-list-files" : "btn-read-file"; ?>

								<span class="<?= $action_class ?>" data-project="<?= $project->PROJECT_ID ?>" data-id="<?= $file["name"] ?>"
									  data-name="<?= $file["name"] ?>" data-resource="<?= $this->basePath() ?>/public/FileManager/File/read">
									<i class="<?= $extension_icon ?> icon"></i><?= $file["name"] ?>
								</span>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</div>
		<?php endforeach; ?>
	<?php endif; ?>

	<script type="text/javascript">
		$('.ui.dropdown').dropdown();
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $intl->translate($this->param("message")) ?>!
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>