-----------------------------------------------------------------------------
--  DATABASE SCHEMA
--
--  TABLE PHS_PROJECT
--  Projects's table
--
--  TABLE PHS_FILE
--  File's table
--
-----------------------------------------------------------------------------

-- TABLE PHS_PROJECT
CREATE TABLE PHS_PROJECT
(
    PROJECT_ID           NUMERIC(4,0)            NOT NULL,
    PROJECT_NAME         VARCHAR2(100)           NOT NULL,
    CONFIG_FILE          VARCHAR2(512)           NOT NULL,
    USER_ID              NUMERIC(4,0)            NOT NULL,
    STATE                CHAR(1)                 NOT NULL,
    RECORD_DATE          TIMESTAMP               NOT NULL
);

ALTER TABLE PHS_PROJECT ADD CONSTRAINT PHS_PROJECT_PK
PRIMARY KEY (PROJECT_ID);

ALTER TABLE PHS_PROJECT ADD CONSTRAINT PHS_PROJECT_FK_USER
FOREIGN KEY (USER_ID) REFERENCES DPM_USER (USER_ID);

ALTER TABLE PHS_PROJECT ADD CONSTRAINT PHS_PROJECT_STATE_CK
CHECK (STATE IN ('A', 'I'));

CREATE TRIGGER PHS_PROJECT_BI_TR
BEFORE INSERT ON PHS_PROJECT
FOR EACH ROW ENABLE
BEGIN
    SELECT SYSDATE INTO :NEW.RECORD_DATE FROM DUAL;
END;
/

CREATE TABLE PHS_FILE
(
    FILE_ID              NUMERIC(4,0)            NOT NULL,
    FILE_NAME           VARCHAR2(100)            NOT NULL,
    USER_ID              NUMERIC(4,0)            NOT NULL,
    STATE                CHAR(1)                 NOT NULL,
    RECORD_DATE          TIMESTAMP               NOT NULL
);

ALTER TABLE PHS_FILE ADD CONSTRAINT PHS_FILE_PK
PRIMARY KEY (FILE_ID);

ALTER TABLE PHS_FILE ADD CONSTRAINT PHS_FILE_FK_USER
FOREIGN KEY (USER_ID) REFERENCES DPM_USER (USER_ID);

ALTER TABLE PHS_FILE ADD CONSTRAINT PHS_FILE_STATE_CK
CHECK (STATE IN ('A', 'I'));

CREATE TRIGGER PHS_FILE_BI_TR
BEFORE INSERT ON PHS_FILE
FOR EACH ROW ENABLE
BEGIN
    SELECT SYSDATE INTO :NEW.RECORD_DATE FROM DUAL;
END;
/