<!doctype html>
<?php $config = include "config/application.config.php"; ?>
<html lang="<?= $config['environment']['locale'] ?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="icon" href="<?= $this->basePath() ?>/public/img/catcher/lure-module.png" type="image/x-icon" />
	<link rel="shortcut icon" href="<?= $this->basePath() ?>/public/catcher/lure-module.png" />

	<!-- responsive metatag -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<?php
		$config = include("module/Catcher/config/user.config.php");
		$this->setTitle($config["project"]["name"]); $title = $this->getTitle();
	?>

	<title><?= $this->getTitle() ?></title>

	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/catcher/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/catcher/fa-svg-with-js.css" />
	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/catcher/css-loader.css" />

</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="<?= $this->basePath() ?>">
	  	<img src="<?= $this->basePath() ?>/public/img/catcher/lure-module.png" height="30" class="d-inline-block align-top" alt="">
	  	<?= $title ?>
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="<?= $this->basePath() ?>/public/Catcher">Catcher <span class="sr-only">(current)</span></a>
	      </li>
	    </ul>
	  </div>
	</nav><br />

	<div class="container">
		<?= $this->content() ?>
	</div>

	<script src="<?= $this->basePath(); ?>/public/js/catcher/jquery-3.3.1.min.js"></script>
	<script src="<?= $this->basePath(); ?>/public/js/catcher/popper-1.12.9.min.js"></script>
	<script src="<?= $this->basePath(); ?>/public/js/catcher/bootstrap.min.js"></script>

	<script src="<?= $this->basePath(); ?>/public/js/catcher/fontawesome-all.min.js"></script>

	<script src="<?= $this->basePath(); ?>/public/js/catcher/fasterjs.js"></script>

	<!-- update page title -->
	<?php if ($this->getTitle() !== $title): ?>
		<script type="text/javascript">
			$("head title").text($("head title").text() + ' - <?= $this->getTitle() ?>');
		</script>
	<?php endif; ?>

</body>

</html>